[versions]
sidebar = "26.6-SNAPSHOT"

alessiodp-parties = "3.2.9"
paf = "1.5.4-RELEASE"
paf-dev = "1.0.239"
paf-redis = "1.0.3-SNAPSHOT"

slf4j = "2.0.7"
hikaricp = "5.0.1"
bstats = "3.0.2"

swm = "2.2.1"
aswm = "1.20-R0.1-SNAPSHOT"

vault = "1.7"
papi = "2.12.2"
vipfeatures = "1.3.0-SNAPSHOT"
citizens = "2.0.30-SNAPSHOT"

paperlib = "1.0.8"
mojang-datafixerupper = "9.0.19"
mojang-brigadier = "1.3.10"
spigot-v18 = "1.8.8-R0.1-SNAPSHOT"
spigot-v1122 = "1.12.2-R0.1-SNAPSHOT"
spigot-v1144 = "1.14.4-R0.1-SNAPSHOT"
spigot-v1165 = "1.16.5-R0.1-SNAPSHOT"
spigot-v1171 = "1.17.1-R0.1-SNAPSHOT"
spigot-v1182 = "1.18.2-R0.1-SNAPSHOT"
spigot-v1193 = "1.19.3-R0.1-SNAPSHOT"
spigot-v1194 = "1.19.4-R0.1-SNAPSHOT"
spigot-v1201 = "1.20.1-R0.1-SNAPSHOT"
spigot-v1202 = "1.20.2-R0.1-SNAPSHOT"
spigot-v1203 = "1.20.3-R0.1-SNAPSHOT"
spigot-v1204 = "1.20.4-R0.1-SNAPSHOT"

[libraries]
sidebar-base = { module = "com.andrei1058.spigot.sidebar:sidebar-base", version.ref = "sidebar" }
sidebar-v18-r3 = { module = "com.andrei1058.spigot.sidebar:sidebar-v1_8_R3", version.ref = "sidebar" }
sidebar-v112-r1 = { module = "com.andrei1058.spigot.sidebar:sidebar-v1_12_R1", version.ref = "sidebar" }
sidebar-v116-r3 = { module = "com.andrei1058.spigot.sidebar:sidebar-v1_16_R3", version.ref = "sidebar" }
sidebar-v117-r1 = { module = "com.andrei1058.spigot.sidebar:sidebar-v1_17_R1", version.ref = "sidebar" }
sidebar-v118-r2 = { module = "com.andrei1058.spigot.sidebar:sidebar-v1_18_R2", version.ref = "sidebar" }
sidebar-v119-r2 = { module = "com.andrei1058.spigot.sidebar:sidebar-v1_19_R2", version.ref = "sidebar" }
sidebar-v119-r3 = { module = "com.andrei1058.spigot.sidebar:sidebar-v1_19_R3", version.ref = "sidebar" }
sidebar-v120-r1 = { module = "com.andrei1058.spigot.sidebar:sidebar-v1_20_R1", version.ref = "sidebar" }
sidebar-v120-r2 = { module = "com.andrei1058.spigot.sidebar:sidebar-v1_20_R2", version.ref = "sidebar" }
sidebar-v120-r3 = { module = "com.andrei1058.spigot.sidebar:sidebar-v1_20_R3", version.ref = "sidebar" }
sidebar-v120-r4 = { module = "com.andrei1058.spigot.sidebar:sidebar-v1_20_R4", version.ref = "sidebar" }

slf4j = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

swm = { module = "com.grinderwolf:slimeworldmanager-api", version.ref = "swm" }
aswm = { module = "com.infernalsuite.aswm:api", version.ref = "aswm" }

alessiodp-parties = { module = "com.alessiodp.parties:parties-api", version.ref = "alessiodp-parties" }
paf = { module = "de.simonsator:Party-and-Friends-MySQL-Edition-Spigot-API", version.ref = "paf" }
paf-dev = { module = "de.simonsator:DevelopmentPAFSpigot", version.ref = "paf-dev" }
paf-redis = { module = "de.simonsator:Spigot-Party-API-For-RedisBungee", version.ref = "paf-redis" }

vault = { module = "net.milkbowl.vault:VaultAPI", version.ref = "vault" }
papi = { module = "me.clip:placeholderapi", version.ref = "papi" }
vipfeatures = { module = "com.andrei1058.vipfeatures:vipfeatures-api", version.ref = "vipfeatures" }
citizens = { module = "net.citizensnpcs:citizens-main", version.ref = "citizens" }

paperlib = { module = "io.papermc:paperlib", version.ref = "paperlib" }
mojang-datafixerupper = { module = "com.mojang:datafixerupper", version.ref = "mojang-datafixerupper" }
mojang-brigadier = { module = "com.mojang:brigadier", version.ref = "mojang-brigadier" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot-v1204" }
spigot = { module = "org.spigotmc:spigot" }
